#include <zephyr/kernel.h>
#include <zephyr/shell/shell.h>
#include <zephyr/shell/shell_uart.h>



/* Shell command: try typing 'my_cmd' at the prompt */
static int my_cmd_fcn(const struct shell *sh, size_t argc, char **argv)
{
    ARG_UNUSED(argc); ARG_UNUSED(argv);
    shell_print(sh, "Hello, this is my custom command!");
    return 0;
}
SHELL_CMD_REGISTER(my_cmd, NULL, "my command", my_cmd_fcn);

int main(void)
{
    printk("Application is starting....\n");
    
}